function plotSubjectMotion(subjectList)
    % Load design generated by SPMGenerateEVs and specify and run GLM in SPM
    
    % Set default home dir for execution on cluster
    homeDir = '/home/fs0/xpsy1114';
    
    % Set default home dir for execution on cluster
    scratchDir = '/home/fs0/xpsy1114/scratch';

    
    % Extract all subjects from subjectList, containing IDs separated by spaces
    tags = strsplit(subjectList);
    % Get total number of subjects
    N = length(tags);    
    
    % Create data structures to store motion summaries
    absMotionTrans = zeros(N,1);
    absMotionRot = zeros(N,1);
    relMotionTrans = zeros(N,1);
    relMotionRot = zeros(N,1);
    % Get instantaneous motion as described by Power 2012
    instMotionCount = zeros(N,1);
    
    % Also collect full data traces
    trans = cell(N,1);
    rot = cell(N,1);
    inst = cell(N,1);
    % And min and max values, for consistent plotting across subjects
    absTransLims = [inf -inf];
    absRotLims = [inf -inf];
    relTransLims = [inf -inf];
    relRotLims = [inf -inf];    
    instLims = [inf -inf];
    
    % Set motion names as found in columns
    motionNames = {'roll','yaw','pitch','x','y','z'};    
    
    % Run through subjects
    for currSub = 1:N
        % Construct preprocessing directory
        preprocDir = fullfile(scratchDir,'data/derivatives',['sub-' tags{currSub}],'func','preproc_clean.feat');
        % Load motion parameters generated by FSL
        motion = load(fullfile(preprocDir,'mc','prefiltered_func_data_mcf.par'));
        % Store for current subject
        trans{currSub} = motion(:,[4 5 6]);
        rot{currSub} = motion(:,[1 2 3]);
        % Calculate Power's 2012 instantaneous motion
        inst{currSub} = [0; sum(abs(diff(trans{currSub})) + abs(diff(rot{currSub})*50),2)];
        % Update limits
        absTransLims = [min(absTransLims(1),min(trans{currSub}(:))) max(absTransLims(2), max(trans{currSub}(:)))];
        absRotLims = [min(absRotLims(1),min(rot{currSub}(:))) max(absRotLims(2), max(rot{currSub}(:)))];
        relTransLims = [min(relTransLims(1),min(min(diff(trans{currSub})))) max(relTransLims(2), max(max(diff(trans{currSub}))))];
        relRotLims = [min(relRotLims(1),min(min(diff(rot{currSub})))) max(relRotLims(2), max(max(diff(rot{currSub}))))];
        instLims = [min(instLims(1),min(inst{currSub})) max(instLims(2), max(inst{currSub}))];        
        % Max total displacement
        absMotionTrans(currSub) = max(sqrt(motion(:,1).^2 + motion(:,2).^2 + motion(:,3).^2));
        absMotionRot(currSub) = max(abs(motion(:,4)) + abs(motion(:,5)) + abs(motion(:,6)));
        % Standard deviation of relative displacement
        relMotionTrans(currSub) = sum(abs(diff(motion(:,1))))+sum(abs(diff(motion(:,2))))+sum(abs(diff(motion(:,3))));
        relMotionRot(currSub) = sum(abs(diff(motion(:,4))))+sum(abs(diff(motion(:,5))))+sum(abs(diff(motion(:,6))));
        % Count how often instantaneous motion exceeds 0.5mm
        instMotionCount(currSub) = sum(inst{currSub} > 0.5);
    end
    
    % Plot translation motion per subject
    rows = ceil(sqrt(N));
    figure();
    for currRow = 1:rows
        for currCol = 1:rows
            currSub = (currRow-1)*rows + currCol;
            if currSub <= N
                subplot(rows,rows,currSub);
                hold on;
                yyaxis left
                plot(trans{currSub});
                ylim(absTransLims);
                ylabel('Abs (mm)');
                yyaxis right
                plot([zeros(1,size(trans{currSub},2)); diff(trans{currSub})]);
                ylim(relTransLims);
                ylabel('Rel (mm)');
                hold off;
                title(tags{currSub});
            end
        end
    end
    
    % Plot rotation motion per subject
    rows = ceil(sqrt(N));
    figure();
    for currRow = 1:rows
        for currCol = 1:rows
            currSub = (currRow-1)*rows + currCol;
            if currSub <= N
                subplot(rows,rows,currSub);
                hold on;
                yyaxis left
                plot(rot{currSub});
                ylim(absRotLims);
                ylabel('Abs (rad)');
                yyaxis right
                plot([zeros(1,size(rot{currSub},2)); diff(rot{currSub})]);
                ylim(relRotLims);
                ylabel('Rel (rad)');
                hold off;
                title(tags{currSub});
            end
        end
    end    
    
    % Plot instantaneous motion per subject
    rows = ceil(sqrt(N));
    figure();
    for currRow = 1:rows
        for currCol = 1:rows
            currSub = (currRow-1)*rows + currCol;
            if currSub <= N
                subplot(rows,rows,currSub);
                hold on;
                plot(inst{currSub});
                plot([1 length(inst{currSub})],[0.5,0.5],'k--');
                hold off;
                ylim(instLims);
                ylabel('Disp (mm)');
                title(tags{currSub});
            end
        end
    end    
    
    % Plot summary of motion
    figure();
    subplot(3,2,1)
    plot(1:N,absMotionTrans,'rx');
    ylabel('Translation (mm)');
    xticks(1:N);
    xticklabels(tags);
    xtickangle(90);
    title('Maximum absolute translation');
    subplot(3,2,2)
    plot(1:N,absMotionRot,'rx');
    ylabel('Rotation (rad)');        
    xticks(1:N);
    xticklabels(tags);
    xtickangle(90);
    title('Maximum absolute rotation');
    subplot(3,2,3);
    plot(1:N,relMotionTrans,'rx');
    ylabel('Translation (mm)');    
    xticks(1:N);
    xticklabels(tags);
    xtickangle(90);
    title('Cumulative relative translation');
    subplot(3,2,4);
    plot(1:N,relMotionRot,'rx')
    ylabel('Rotation (rad)');        
    xticks(1:N);
    xticklabels(tags);
    xtickangle(90);
    title('Cumulative relative rotation');
    subplot(3,2,5);
    hold on;
    plot([1 N],[mean(instMotionCount) + std(instMotionCount),mean(instMotionCount) + std(instMotionCount)],'k--');
    plot(1:N,instMotionCount,'rx')
    hold off;
    ylabel('Count (1)');        
    xticks(1:N);
    xticklabels(tags);
    xtickangle(90);
    title('Count instantaneous movement > 0.5 mm');    
    subplot(3,2,6);
    hold on;
    hist(instMotionCount);
    plot([mean(instMotionCount) + std(instMotionCount), mean(instMotionCount) + std(instMotionCount)], [0, 10], 'k--');
    hold off;
    title('Histogram instantaneous movement > 0.5 mm');        
    
    % Plot thesis figure
    
    figure();
end