#!/bin/bash
# Copy files as downloaded from calpendo to scratch and organise according to BIDS format

# Add the dcm2niix module for conversion of a folder of dcm files to a single nii file. You need an additional line if you do that in a bash script, see https://sharepoint.nexus.ox.ac.uk/sites/NDCN/FMRIB/IT/User%20Guides/Modules.aspx
# These are not currently necessary because I load the module in ~/.local_profile 
#. $MODULESHOME/init/bash
#module load dcm2niix

# Command line argument 1/3: subject number
subjectNumber=$1
echo Calpendo subject number of the data you want to download: $subjectNumber

# Command line argument 2/3: subject tag
subjectTag=$2
echo Subject tag for this subject: $subjectTag

# Command line argument 3/3: image start number (usually 2, but if something went wrong could be 4)
imageStartNumber=$3
echo First image file to load: $imageStartNumber

# Set scratch directory for execution on server
scratchDir=/home/fs0/jacobb/scratch
# If this is not called on the server, but on a laptop connected to the server:
if [ ! -d $scratchDir ]; then
  scratchDir=/Volumes/Scratch_jacobb
fi
# If this is not called on a laptop, but on a mac connected to the server:
if [ ! -d $scratchDir ]; then
  scratchDir=/Users/jacobb/Documents/ServerHome/scratch
fi

# Construct folder generated by calpendo from project code and zero-padded subject number
calpendoDir=F3T_2019_008_$(printf "%03d" $subjectNumber)

# Set data directory where scan files are downloaded to
dataDir=/vols/Data/MRdata/jacobb

# Echo what is going to happen
echo I will transfer files for subject $subjectTag with Calpendo nr $subjectNumber from ${dataDir}/${calpendoDir} to ${scratchDir}/sub-$subjectTag starting from file $imageStartNumber

# Secure-copy all files to scratch
echo 1. Secure-copying all files to scratch

# Change folder to data folder
cd ${dataDir}/${calpendoDir}
# Make directory for images (-p: don't if already exists)
mkdir -p ${scratchDir}/sub-$subjectTag
# Secure copy images to scratch
scp -r images_* ${scratchDir}/sub-$subjectTag
# Secure copy bold folder to scratch
scp -r bold_mbep2d_* ${scratchDir}/sub-$subjectTag
# And change directory to scratch
cd ${scratchDir}/sub-$subjectTag

# Convert dicom folder to nifti file
echo 2. Converting dicom folder to nifti file

# First convert dicom to nifti: move into dicom folder
cd ./bold_mbep2d*
# Add module for dicom to nifti conversion - for some reason you can't do this if it's run on the cluster, so make sure to do it before!
# module add dcm2niix
# Then do dicom conversion
dcm2niix -z y .
# Construct filename as expected from calpendo: find reference bold image, copy its name, but increase the image number by 1
newName=$(echo ../images_$(printf "%03d" $imageStartNumber)_* | sed "s:../images_$(printf "%03d" $imageStartNumber):images_$(printf "%03d" "$(($imageStartNumber+1))"):")
# Rename created nifti image and move up
mv __bold_mbep2d*.nii.gz ../$newName
# Rename created json file and move up
mv __bold_mbep2d*.json ../"${newName%%.*}".json
# Move back to subject folder
cd ${scratchDir}/sub-$subjectTag

# Create folder structure and rename files following BIDS
echo 3. Creating folder structure and renaming files according to BIDS standard

# Create func folder
mkdir -p func
# Rename reference file and move it
mv images_$(printf "%03d" "$((0+$imageStartNumber))")_* func/sub-${subjectTag}_reference.nii.gz
# Rename bold file and move it
mv images_$(printf "%03d" "$((1+$imageStartNumber))")_*.nii.gz func/sub-${subjectTag}_bold.nii.gz
# Rename bold json and move it
mv images_$(printf "%03d" "$((1+$imageStartNumber))")_*.json func/sub-${subjectTag}_bold.json
# Create field map folder
mkdir -p fmap
# Rename magnitude fieldmap file and move it
mv images_$(printf "%03d" "$((2+$imageStartNumber))")_* fmap/sub-${subjectTag}_magnitude.nii.gz
# Rename phase fieldmap file and move it
mv images_$(printf "%03d" "$((3+$imageStartNumber))")_* fmap/sub-${subjectTag}_phasediff.nii.gz
# Create anatomy folder
mkdir -p anat
# Copy second structural (which is bias-field corrected)
mv images_$(printf "%03d" "$((5+$imageStartNumber))")_* anat/sub-${subjectTag}_T1W.nii.gz

# Clean up: remove leftover nifti files and dicom folder
echo 4. Cleaning up: removing leftover image files and dicom folder

# Remove nifti files that still have images_ in their name: these are not renamed and won't be used
rm images_*
# Remove the dicom folder
rm -r bold_mbep2d*